#!/bin/sh
#set -e
if [ "$1" = "configure" ]; then
	chown nobody:nogroup /opt/switchportmapper/log
	chown nobody:nogroup /opt/switchportmapper/ports
	chown nobody:nogroup /opt/switchportmapper/state

	a2ensite switchportmapper.conf
	/etc/init.d/apache2 reload

	chmod 777 /opt/switchportmapper/log
	chmod 777 /opt/switchportmapper/ports
	chmod 777 /opt/switchportmapper/state
	chmod 644 /opt/switchportmapper/etc/switchportmapper.cron
	chmod 755 /opt/switchportmapper/bin/doSwitchMap
	chown root /opt/switchportmapper/bin/doSwitchMap

	a2enmod cgi; a2ensite switchportmapper.conf; service apache2 restart

	download-mibs
	sed -ie 's/^mibs :$/#mibs :/' /etc/snmp/snmp.conf

	if [ -x /usr/sbin/netdisco-mibs-download ]
	then
		/usr/sbin/netdisco-mibs-download
		/usr/sbin/netdisco-mibs-install
	fi
fi

