#!/bin/sh
#set -e
if [ "$1" = "configure" ]; then
	chown nobody:nogroup /opt/switchportmapper/log
	chown nobody:nogroup /opt/switchportmapper/ports
	chown nobody:nogroup /opt/switchportmapper/state

	a2ensite switchportmapper.conf
	/etc/init.d/apache2 reload

	chmod 777 /opt/switchportmapper/log
	chmod 777 /opt/switchportmapper/ports
	chmod 777 /opt/switchportmapper/state
	a2enmod cgi; a2ensite switchportmapper.conf; service apache2 restart

	sed -ie 's/^mibs :$/#mibs :/' /etc/snmp/snmp.conf
fi

